PREFIX : <urn:alhidad:>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?path WHERE {
  ?file a :File ;
        :path ?path ;
        :directory ?dir .
  ?dir :category ?cat .
  ?cat skos:prefLabel ?catLabel .
  FILTER(STRSTARTS(?catLabel, "$CATEGORY"))
}
ORDER BY DESC(?path)
